// config.js
export const hexWidth = 466;
export const hexHeight = 405;
export const baseHexWidth = 466;
export const baseHexHeight = 405;
export const horizontalSpacing = hexWidth * 0.75;
export const verticalSpacing = hexHeight * 0.866;
export const terrainTypes = [
    'water', 
    'wetland', 
    'plains', 
    'forest', 
    'mountain', 
    'urban', 
    'ruins', 
    'wheatfield', 
    'snow', 
    'snowmountain', 
    'hills', 
    'snowhills', 
    'dune', 
    'volcano', 
    'badmountain', 
    'snowvolcano', 
    'badvolcano'
  ];
  
export const terrainImages = {};

export const terrainConfig = {
  mountain: {
    chance: 10,
    color: "#f0f0f0",
    size: 70,
    names: [
      "Ashen Spire of the Fallen",
      "Crimson Blackpeak",
      "Duskborne Pinnacle",
      "Bleak Crown",
      "Thorned Aerie",
      "Emberveil Crags",
      "Forsaken Apex",
      "Gravebound Summit",
      "Mournful Monolith",
      "Sorrow’s Crest",
      "Ebonridge",
      "Gloam’s End",
      "Obsidian Ledge",
      "Shattered Zenith",
      "Wraith’s Rest",
      "Spectral Tor",
      "Nightfall Spire",
      "Sable Crown",
      "Desolation Peak",
      "Void’s Embrace",
      "Haunted Escarpment",
      "Dreadspire",
      "Eclipse Crag",
      "Cindered Heights",
      "Malediction Mound",
      "Forgotten Sentinel",
      "Mourning Ridge",
      "Shadowed Pinnacle",
      "Ruined Colossus",
      "Gloomspire",
      "Abyssal Summit",
      "Sundered Peak",
      "Twilight Apex",
      "Dire Spire",
      "Woe’s Crest",
      "Phantom Height",
      "Grim Monolith",
      "Dismal Butte",
      "Faded Summit",
      "Sombre Bluff",
      "Eclipsed Altitude",
      "Dimmed Spire",
      "Forsworn Mountain",
      "Pale Ascendant",
      "Grievous Knoll",
      "Bleak Overlook",
      "Duskwrought Pinnacle",
      "Somber Ridge",
      "Forlorn Eminence",
      "Despairing Tor"
    ],
    keywords: {
      list: [
        "Soulforge Ascent",
        "Hollow Reverie",
        "Gloombound",
        "Shade’s Dominion",
        "Dusk Enigma",
        "Forsaken Echo",
        "Sable Benediction",
        "Emberwraith",
        "Phantom Mantle",
        "Raven’s Grasp",
        "Oblivion Shroud",
        "Nocturne Veil",
        "Bleak Benediction",
        "Eternal Mourning",
        "Desolation’s Whisper",
        "Dread Manifest",
        "Cursed Ascendancy",
        "Wraithbound",
        "Netherpulse",
        "Spectral Fury",
        "Abyssal Howl",
        "Grim Resonance",
        "Twilight Curse",
        "Shadowed Lament",
        "Ebon Requiem",
        "Forsworn Call",
        "Melancholy Echo",
        "Dismal Omen",
        "Mourning Whisper",
        "Dire Chorus",
        "Sorrowbound",
        "Grim Echo",
        "Twilight Wail",
        "Haunt of Ages",
        "Phantom Dirge",
        "Woe’s Hymn",
        "Forsaken Song",
        "Abyssal Cry",
        "Morose Pulse",
        "Gloom Rapture",
        "Shattered Choir",
        "Despairing Chant",
        "Dusk Sonata",
        "Lamenting Accord",
        "Sable Melody",
        "Nether Symphony",
        "Eclipsed Aria",
        "Haunted Rhythm",
        "Mournful Cadence",
        "Dirge of Shadows"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  ruins: {
    chance: 100,
    color: "#e8e8e8",
    size: 70,
    names: [
      "Ruin of the Weeping King",
      "Forsaken Basilica",
      "Shattered Citadel",
      "Sepulcher of Sorrow",
      "Crumbled Sanctum",
      "Bleak Reliquary",
      "Haunted Hall",
      "Gloomhaven",
      "Eclipsed Abbey",
      "Dilapidated Dais",
      "Mournful Keep",
      "Specter’s Vault",
      "Oblivion's Echo",
      "Deserted Reliquary",
      "Vestige of the Damned",
      "Fallen Pantheon",
      "Shadowed Ruin",
      "Abandoned Catacomb",
      "Shrouded Necropolis",
      "Lamented Spire",
      "Broken Archway of Despair",
      "Forgotten Shrine",
      "Duskfall Ruins",
      "Cursed Courtyard",
      "Forsworn Remains",
      "Ghastly Citadel",
      "Mournful Mausoleum",
      "Spectral Bastion",
      "Phantom Ruins",
      "Wraithborne Hall",
      "Ebon Relics",
      "Graveyard Ruin",
      "Nocturne Remnant",
      "Dilapidated Reliquary",
      "Somber Bastion",
      "Obsidian Ruin",
      "Ravaged Monastery",
      "Crumbling Portico",
      "Ashen Ruin",
      "Desolate Edifice",
      "Lost Convent",
      "Ruined Sanctuary",
      "Dire Remnants",
      "Forgotten Keep",
      "Decayed Fortress",
      "Sundered Hall",
      "Dismal Ruin",
      "Haunted Vestige",
      "Pale Relic",
      "Sombre Remnant",
      "Eternal Ruin",
      "Shattered Cloister",
      "Mournful Hall",
      "Gloaming Ruins",
      "Phantom Citadel",
      "Forsaken Portico",
      "Broken Reliquary",
      "Desolation Hall",
      "Nightshade Ruin",
      "Cursed Edifice",
      "Wraith Sanctum"
    ],
    keywords: {
      list: [
        "Ethereal Decay",
        "Phantom Relics",
        "Doomed Reverence",
        "Cursed Vestige",
        "Sable Remnants",
        "Lost Benediction",
        "Ghastly Pilgrimage",
        "Wraith Covenant",
        "Desolate Echo",
        "Mourning Atonement",
        "Spectral Gravestones",
        "Bleak Liturgy",
        "Nether Relic",
        "Nocturnal Ruin",
        "Hollow Dirge",
        "Sorrow’s Relic",
        "Dread Benediction",
        "Forsaken Inheritance",
        "Malediction Reliquary",
        "Vesper Graves",
        "Forgotten Epitaph",
        "Crumbled Testament",
        "Abyssal Archive",
        "Shadowed Chronicle",
        "Decayed Oath",
        "Eclipsed Testament",
        "Mournful Ledger",
        "Grave Murmur",
        "Sepulchral Whisper",
        "Ruined Memory",
        "Desolation Scroll",
        "Phantom Ledger",
        "Forsworn Record",
        "Oblivion Archive",
        "Haunted Annals",
        "Cryptic Relic",
        "Spectral Record",
        "Wraith Manuscript",
        "Nocturne Memoir",
        "Dilapidated Chronicle",
        "Gloomy Testament",
        "Cursed Annals",
        "Sable Archive",
        "Morose Record",
        "Forsaken Ledger",
        "Dismal Memoir",
        "Eternal Inscription",
        "Grim Epitaph",
        "Somber Chronicle"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  urban: {
    chance: 100,
    color: "#d8d8d8",
    size: 50,
    names: [
      "Cursed Market",
      "Forsaken Borough",
      "Duskfall Quarter",
      "Haunted Alley",
      "Eclipsed Haven",
      "Obsidian District",
      "Mourning Pavements",
      "Gloomvale",
      "Phantom Ward",
      "Wraith's Crossing",
      "Shattered Promenade",
      "Spectral Crossroads",
      "Desolation Square",
      "Bleak Bastion",
      "Ebon Outskirts",
      "Twilight Precinct",
      "Nocturne Lane",
      "Shadowed Block",
      "Eternal Sprawl",
      "Ruined Refuge",
      "Faded Metropolis",
      "Dismal Quarter",
      "Forsworn Alley",
      "Ghostly Bypass",
      "Grim Arcade",
      "Sable Street",
      "Mournful Byway",
      "Eclipsed Avenue",
      "Wraith Borough",
      "Abandoned Concourse",
      "Haunted Corridor",
      "Desolate Plaza",
      "Forlorn Passage",
      "Lost Precinct",
      "Oblivion District",
      "Crumbling Suburb",
      "Dusk City",
      "Phantom Locale",
      "Nether Market",
      "Bleak Promenade",
      "Forgotten District",
      "Somber Row",
      "Gloom Street",
      "Spectral Bypass",
      "Waning Market",
      "Dreary Borough",
      "Shadowed Conclave",
      "Cursed Avenue",
      "Nocturnal Crossing",
      "Despair District"
    ],
    keywords: {
      list: [
        "Forgotten Commune",
        "Doomed Assembly",
        "Forsaken Trade",
        "Cursed Gathering",
        "Sable Conglomerate",
        "Phantom Hub",
        "Wraithbound District",
        "Ebon Collation",
        "Graveyard Faction",
        "Nether Syndicate",
        "Mourning Collective",
        "Dusk Assembly",
        "Hollow Mart",
        "Desolation Council",
        "Twilight Court",
        "Spectral Conclave",
        "Bleak Parliament",
        "Eternal Guild",
        "Oblivion Plaza",
        "Nocturne Summit",
        "Faded Union",
        "Gloam Assembly",
        "Forsworn Coalition",
        "Grim Convergence",
        "Somber Congress",
        "Desolate Assembly",
        "Mournful Syndicate",
        "Shadowed Union",
        "Dismal Council",
        "Cryptic Assembly",
        "Lost Confederation",
        "Eclipsed Circle",
        "Phantom Order",
        "Waning Assembly",
        "Forsaken Consulate",
        "Gloom Syndicate",
        "Spectral Consortium",
        "Dread Gathering",
        "Nocturne Council",
        "Abandoned Fellowship",
        "Hollow Alliance",
        "Faded Parliament",
        "Obsidian Congregation",
        "Cursed Fellowship",
        "Dusk Union",
        "Eternal Order",
        "Grave Collective",
        "Shadowed Summit",
        "Bleak Consortium",
        "Forsworn Order"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  forest: {
    chance: 20,
    color: "#c8e6c9",
    size: 50,
    names: [
      "Twilight Grove",
      "Whispering Thicket",
      "Gloomwood",
      "Mournwood",
      "Faded Copse",
      "Ebon Grove",
      "Shadowed Arboretum",
      "Wraithwood",
      "Forsaken Glade",
      "Duskroot Forest",
      "Cursed Canopy",
      "Hallowed Timberland",
      "Gravewood Vale",
      "Silenced Wilds",
      "Netherwood",
      "Phantom Woodlands",
      "Bleak Bramble",
      "Haunted Woodland",
      "Eclipsed Underwood",
      "Lamenting Leaves",
      "Dreary Grove",
      "Misty Thicket",
      "Somber Woods",
      "Duskwind Forest",
      "Gloaming Copse",
      "Eternal Grove",
      "Forsworn Timber",
      "Dusky Arbor",
      "Ghostwood",
      "Cimmerian Grove",
      "Pale Forest",
      "Ebon Timber",
      "Shadeleaf Wood",
      "Waning Grove",
      "Murky Thicket",
      "Mournful Orchard",
      "Desolate Wood",
      "Hollow Forest",
      "Duskwood Realm",
      "Forlorn Arboretum",
      "Sable Sylva",
      "Bleak Woodland",
      "Twilight Copse",
      "Phantom Arboretum",
      "Nocturne Grove",
      "Fallen Leaves Wood",
      "Dismal Timber",
      "Wraithwood Glade",
      "Shadowed Sylvan"
    ],
    keywords: {
      list: [
        "Enshadowed",
        "Duskwood",
        "Soulbound Sapling",
        "Grave Root",
        "Eternal Canopy",
        "Phantom Foliage",
        "Hollow Thicket",
        "Mournful Briar",
        "Nocturne Vines",
        "Wraithborne",
        "Forsaken Sprout",
        "Bleak Bud",
        "Cursed Sapling",
        "Twilight Bloom",
        "Nether Sprig",
        "Spectral Orchard",
        "Gloom Seed",
        "Doomed Grove",
        "Shadowbloom",
        "Ebon Blossom",
        "Mystic Canopy",
        "Waning Leaf",
        "Faded Sprout",
        "Grim Bloom",
        "Somber Seed",
        "Haunted Frond",
        "Dusky Petal",
        "Gloam Bud",
        "Forsworn Bloom",
        "Melancholy Sprig",
        "Pale Seedling",
        "Nocturne Blossom",
        "Phantom Frond",
        "Eclipsed Sprout",
        "Sable Petal",
        "Mourning Leaf",
        "Shadowed Bloom",
        "Dusk Petal",
        "Twilight Frond",
        "Gloomy Sprig",
        "Cursed Bloom",
        "Eternal Seed",
        "Wraith Leaf",
        "Desolate Bud",
        "Forsaken Frond",
        "Somber Blossom",
        "Bleak Sprout",
        "Nether Leaf",
        "Dismal Bloom"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  plains: {
    chance: 15,
    color: "#e0e0e0",
    size: 50,
    names: [
      "Desolation Expanse",
      "Barren Wastes",
      "Sorrowful Fields",
      "Haunted Barrens",
      "Forsaken Meadow",
      "Gloomsteppe",
      "Wraith Plains",
      "Dusk Meadow",
      "Mournful Flatlands",
      "Eclipse Prairie",
      "Nocturne Fields",
      "Bleak Farmland",
      "Eternal Expanse",
      "Phantom Pastures",
      "Oblivion Downs",
      "Cursed Openlands",
      "Faded Frontier",
      "Twilight Heath",
      "Shadowed Ground",
      "Grave Plains",
      "Deserted Meadow",
      "Forsworn Fields",
      "Somber Expanse",
      "Lost Pasture",
      "Dismal Plains",
      "Grim Grasslands",
      "Ebon Heath",
      "Melancholy Meadows",
      "Waning Fields",
      "Bleak Acreage",
      "Haunted Sward",
      "Dusk Farmlands",
      "Nether Prairie",
      "Mournful Fields",
      "Forsaken Expanse",
      "Gloomy Farmland",
      "Eclipse Downs",
      "Desolate Acreage",
      "Phantom Heath",
      "Nocturne Meadow",
      "Cursed Grassland",
      "Faded Expanse",
      "Sable Plains",
      "Grave Acre",
      "Shadow Heath",
      "Dismal Pastures",
      "Twilight Expanse",
      "Somber Fields",
      "Lost Acreage",
      "Eternal Meadow",
      "Grim Downs"
    ],
    keywords: {
      list: [
        "Forsaken Sowing",
        "Soul-Faded",
        "Grim Reap",
        "Wraith Harvest",
        "Cursed Till",
        "Ebon Seed",
        "Desolation Grain",
        "Phantom Fallow",
        "Nocturne Acre",
        "Bleak Yielder",
        "Gloom Spire",
        "Twilight Sward",
        "Eclipse Crop",
        "Oblivion Farmstead",
        "Mournful Sprout",
        "Shadowed Plow",
        "Dusk Cultivation",
        "Hollow Harvest",
        "Forsworn Reap",
        "Desolate Sowing",
        "Mournful Yield",
        "Waning Reap",
        "Sable Harvest",
        "Grave Till",
        "Dismal Grain",
        "Eternal Sow",
        "Phantom Acre",
        "Nocturne Tiller",
        "Bleak Seeder",
        "Gloomy Cultivation",
        "Twilight Harvest",
        "Forsaken Crop",
        "Cursed Acreage",
        "Ebon Till",
        "Grim Seeder",
        "Somber Cultivation",
        "Dusk Reap",
        "Shadow Sow",
        "Oblivion Grain",
        "Lost Acre",
        "Mournful Crop",
        "Wraith Seeder",
        "Forsworn Till",
        "Gloom Harvest",
        "Desolation Tiller",
        "Eclipse Acre",
        "Nocturne Sow",
        "Bleak Crop",
        "Sable Reap",
        "Eternal Seeder",
        "Grave Cultivation"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  water: {
    chance: 25,
    color: "#b3e5fc",
    size: 50,
    names: [
      "Abyssal River",
      "Sorrow's Cascade",
      "Eternal Brook",
      "Haunted Tributary",
      "Phantom Lake",
      "Obsidian Pool",
      "Cursed Waters",
      "Wraithfall Reservoir",
      "Gloomtide",
      "Twilight Estuary",
      "Bleak Waters",
      "Nocturne Inlet",
      "Mournful Flood",
      "Duskwater",
      "Shadowed Shore",
      "Gravewater",
      "Eclipse Delta",
      "Forsaken Basin",
      "Nether Stream",
      "Lamenting Lagoon",
      "Despairing Current",
      "Dismal Run",
      "Forsworn Flow",
      "Somber Tributary",
      "Ebon Cascade",
      "Misty Brook",
      "Gloaming River",
      "Forgotten Inlet",
      "Faded Torrent",
      "Waning Waters",
      "Oblivion Brook",
      "Phantom Delta",
      "Gloomed Pool",
      "Cursed Cascade",
      "Haunted Rivulet",
      "Shadowed Current",
      "Nocturne Brook",
      "Dusk River",
      "Bleak Flow",
      "Grim Estuary",
      "Mournful Surge",
      "Forsaken Rill",
      "Eternal Stream",
      "Wraith Cascade",
      "Dusky Rivulet",
      "Phantom Flow",
      "Nether Torrent",
      "Desolate Delta",
      "Twilight Brook",
      "Gloam Surge",
      "Eclipse Rill"
    ],
    keywords: {
      list: [
        "Abyssal Current",
        "Phantom Surge",
        "Cursed Flow",
        "Wraith Tide",
        "Oblivion Drift",
        "Nocturne Rill",
        "Gloom Ripple",
        "Desolation Deluge",
        "Eternal Torrent",
        "Mournful Swell",
        "Shadowed Plunge",
        "Dusk Flood",
        "Bleak Cascade",
        "Forsaken Spill",
        "Grave Undercurrent",
        "Twilight Stream",
        "Nether Wave",
        "Hollow Current",
        "Spectral Surge",
        "Ebon Deluge",
        "Forsworn Flow",
        "Somber Drift",
        "Melancholy Tide",
        "Eclipse Surge",
        "Haunted Rill",
        "Waning Flow",
        "Phantom Ripple",
        "Cursed Surge",
        "Dismal Current",
        "Gloomy Drift",
        "Nocturne Wave",
        "Oblivion Flood",
        "Mournful Rill",
        "Shadow Cascade",
        "Desolate Current",
        "Twilight Rill",
        "Nether Deluge",
        "Faded Surge",
        "Sable Current",
        "Grim Ripple",
        "Eternal Drift",
        "Forsaken Tide",
        "Bleak Plunge",
        "Wraith Deluge",
        "Dusky Wave",
        "Phantom Torrent",
        "Gloam Flow",
        "Eclipse Current",
        "Nocturne Deluge",
        "Mournful Tide",
        "Hollow Surge"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  wetland: {
    chance: 30,
    color: "#a0d6b4",
    size: 50,
    names: [
      "Mired Hallow",
      "Forsaken Bog",
      "Sullen Marsh",
      "Haunted Fen",
      "Dusk Mire",
      "Cursed Slough",
      "Gloom Quagmire",
      "Ebon Swamp",
      "Wraith Mire",
      "Twilight Bog",
      "Bleak Marshlands",
      "Oblivion Fen",
      "Shadowed Mire",
      "Nocturne Quagmire",
      "Mournful Slough",
      "Grave Marsh",
      "Eclipse Bog",
      "Spectral Mire",
      "Nether Quagmire",
      "Lament Marsh",
      "Forsworn Mire",
      "Dusky Bog",
      "Desolate Marsh",
      "Misty Fen",
      "Gloaming Mire",
      "Somber Quagmire",
      "Eternal Slough",
      "Faded Marsh",
      "Dismal Mire",
      "Waning Bog",
      "Phantom Quagmire",
      "Haunted Slough",
      "Bleak Mire",
      "Cursed Fen",
      "Obsidian Marsh",
      "Shadowed Quagmire",
      "Nocturne Mire",
      "Mournful Bog",
      "Forsaken Slough",
      "Gloom Marsh",
      "Twilight Mire",
      "Eclipse Quagmire",
      "Despairing Marsh",
      "Wraith Fen",
      "Dusky Slough",
      "Nether Mire",
      "Lamenting Bog",
      "Grave Quagmire",
      "Forsworn Marsh",
      "Somber Mire",
      "Oblivion Slough"
    ],
    keywords: {
      list: [
        "Basilisk Pools",
        "Rot Infestation",
        "Kindred Colonies",
        "Octopus Nesting",
        "Wormface Congregations",
        "Demi-Human Huts",
        "Fire Cleansing",
        "Deathblight Banks",
        "Crystal Contamination",
        "Erdtree Rot",
        "Dragon Sacrifice",
        "Night Brews",
        "Albinauric Defects",
        "Omenkiller Pits",
        "Carian Runoff",
        "Troll Waste",
        "Follower Mounds",
        "Grafted Dumps",
        "Forsworn Ooze",
        "Somber Drip",
        "Mired Rot",
        "Gloomy Spores",
        "Nocturne Ooze",
        "Cursed Infestation",
        "Eternal Mire",
        "Phantom Drizzle",
        "Dusk Decay",
        "Wraith Pools",
        "Oblivion Ooze",
        "Desolate Drip",
        "Rotting Bloom",
        "Mournful Sludge",
        "Bleak Residue",
        "Shadowed Ooze",
        "Forsaken Drip",
        "Nether Muck",
        "Dismal Spores",
        "Sable Drizzle",
        "Grave Ooze",
        "Haunted Muck",
        "Forsworn Sludge",
        "Eclipse Rot",
        "Nocturne Mires",
        "Somber Contagion",
        "Faded Ooze",
        "Waning Drip",
        "Eroded Residue",
        "Mired Decay",
        "Gloom Infestation",
        "Cursed Muck"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  wheatfield: {
    chance: 40,
    color: "#f3e5ab",
    size: 50,
    names: [
      "Cursed Harvest",
      "Wraith-Felled Fields",
      "Doomed Acreage",
      "Desolation Crop",
      "Haunted Farmlands",
      "Phantom Yield",
      "Bleak Barley",
      "Forsaken Grain",
      "Mournful Wheat",
      "Gloom Harvest",
      "Eclipse Meadows",
      "Shadowed Tillage",
      "Nether Sown",
      "Twilight Reap",
      "Oblivion Cropland",
      "Grave Harvest",
      "Dusked Agronomy",
      "Ebon Fields",
      "Spectral Farrow",
      "Lamenting Acre",
      "Forsworn Harvest",
      "Somber Fields",
      "Desolate Grain",
      "Waning Crop",
      "Forsaken Silo",
      "Grim Yield",
      "Misty Harvest",
      "Gloaming Fields",
      "Nocturne Acreage",
      "Cursed Plow",
      "Faded Harvest",
      "Bleak Acreage",
      "Haunted Reap",
      "Phantom Till",
      "Shadowed Sward",
      "Eternal Agronomy",
      "Dusk Fields",
      "Obsidian Harvest",
      "Mournful Reap",
      "Forsworn Grain",
      "Gloomy Acre",
      "Twilight Tillage",
      "Nether Crop",
      "Dismal Yield",
      "Sable Fields",
      "Grave Tiller",
      "Forsaken Acre",
      "Somber Reap",
      "Desolation Sown",
      "Wraith Agronomy",
      "Eclipsed Harvest"
    ],
    keywords: {
      list: [
        "Kindred Infestation",
        "Demi-Human Raiders",
        "Fire Barns",
        "Erdtree Patrols",
        "Deathroot Soil",
        "Flame Hideouts",
        "Albinauric Labor",
        "Omen Burial Sites",
        "Scion Nesting",
        "Rot Spore Spread",
        "Night Grain",
        "Follower Terraces",
        "Nomad Caravans",
        "Troll Plows",
        "Carian Fertilizer",
        "Dragon Offerings",
        "Black Sabotage",
        "Perfumer Gardens",
        "Forsworn Till",
        "Somber Acre",
        "Dusk Harvest",
        "Gloom Seeder",
        "Phantom Agronomy",
        "Wraith Crop",
        "Cursed Yield",
        "Bleak Sowing",
        "Eternal Tiller",
        "Mournful Seed",
        "Shadowed Plow",
        "Desolate Acreage",
        "Forsaken Cultivation",
        "Nocturne Yield",
        "Dismal Harvest",
        "Grim Agronomy",
        "Sable Till",
        "Waning Cultivation",
        "Oblivion Crop",
        "Twilight Sowing",
        "Nether Yield",
        "Forsworn Reap",
        "Somber Seeder",
        "Desolation Tiller",
        "Wraith Seed",
        "Gloom Sown",
        "Bleak Tiller",
        "Eternal Acre",
        "Mournful Cultivation",
        "Shadowed Harvest",
        "Forsworn Crop",
        "Dusk Reap"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  snow: {
    chance: 15,
    color: "#e0f7fa",
    size: 50,
    names: [
      "Frostbitten Expanse",
      "Icy Desolation",
      "Crystal Shard Wastes",
      "Glacial Mourning",
      "Winter's Dread",
      "Frozen Barrens",
      "Chillbound Expanse",
      "Shivering Wastes",
      "Snowveil Plains",
      "Icy Void",
      "Frosted Expanse",
      "Glacial Wasteland",
      "Winter's Bane",
      "Frozen Solitude",
      "Crystaline Frost",
      "Icy Ruin",
      "Chilling Expanse",
      "Frostbound Plains",
      "Glacial Despair",
      "Winter's Grasp",
      "Snowbound Expanse",
      "Frozen Abyss",
      "Chill Wastes",
      "Icy Dominion",
      "Frosted Wastes",
      "Glacial Silence",
      "Winter's Shroud",
      "Snowbound Desolation",
      "Frozen Dusk",
      "Chill Expanse",
      "Icy Gloom",
      "Frosted Despair",
      "Glacial Dirge",
      "Winter's Lament",
      "Snowbound Mourning",
      "Frozen Twilight",
      "Chillfall Expanse",
      "Icy Mourn",
      "Frosted Lull",
      "Glacial Hush",
      "Winter's Echo",
      "Snowbound Silence",
      "Frozen Mourn",
      "Chill Veil",
      "Icy Twilight",
      "Frosted Gloom",
      "Glacial Requiem",
      "Winter's Solace",
      "Snowbound Woe"
    ],
    keywords: {
      list: [
        "Frostmourne",
        "Glacial Sorrow",
        "Snowbound Woe",
        "Icy Dirge",
        "Winter's Grief",
        "Frosted Lament",
        "Chill Requiem",
        "Frozen Echo",
        "Crystaline Dirge",
        "Icy Solace",
        "Frostbound Mourn",
        "Glacial Lull",
        "Winter's Echo",
        "Snowbound Requiem",
        "Frozen Sigh",
        "Chill Whisper",
        "Icy Sorrow",
        "Frosted Requiem",
        "Glacial Mourning",
        "Winter's Tear",
        "Snowbound Silence",
        "Frozen Lament",
        "Chill Dirge",
        "Icy Mourn",
        "Frosted Sorrow",
        "Glacial Grief",
        "Winter's Hush",
        "Snowbound Cry",
        "Frozen Wail",
        "Chill Sigh",
        "Icy Whisper",
        "Frostbound Cry",
        "Glacial Shiver",
        "Winter's Wail",
        "Snowbound Tear",
        "Frozen Shard",
        "Chill Eulogy",
        "Icy Lullaby",
        "Frosted Sigh",
        "Glacial Mourn",
        "Winter's Chant",
        "Snowbound Eulogy",
        "Frozen Tear",
        "Chill Grief",
        "Icy Requiem",
        "Frosted Lullaby",
        "Glacial Sigh",
        "Winter's Soliloquy",
        "Snowbound Mourn",
        "Frozen Eulogy",
        "Chill Cry"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  snowmountain: {
    chance: 10,
    color: "#e0f7fa",
    size: 70,
    names: [
      "Shivering Pinnacle",
      "Frostwrought Summit",
      "Icy Dreadpeak",
      "Glacial Desolation",
      "Chilling Apex",
      "Frozen Crest",
      "Snowbound Peak",
      "Crystaline Summit",
      "Icy Zenith",
      "Frostbound Pinnacle",
      "Glacial Spire",
      "Winter's Crown",
      "Snowclad Summit",
      "Frozen Aerie",
      "Icy Apex",
      "Frosted Pinnacle",
      "Glacial Crest",
      "Winter's Summit",
      "Snowbound Zenith",
      "Frozen Dreadpeak",
      "Icy Spire",
      "Frostwrought Apex",
      "Glacial Crown",
      "Winter's Pinnacle",
      "Snowbound Crest",
      "Frozen Zenith",
      "Icy Dreadspire",
      "Frostbound Summit",
      "Glacial Apex",
      "Winter's Desolation",
      "Snowclad Pinnacle",
      "Frozen Crest",
      "Icy Summit",
      "Frosted Apex",
      "Glacial Dreadpeak",
      "Winter's Woe",
      "Snowbound Spire",
      "Frozen Crown",
      "Icy Zenith",
      "Frostwrought Pinnacle",
      "Glacial Spire",
      "Winter's Ire",
      "Snowclad Apex",
      "Frozen Dreadspire",
      "Icy Crown",
      "Frostbound Zenith",
      "Glacial Summit",
      "Winter's Shiver",
      "Snowbound Dreadpeak",
      "Frozen Apex",
      "Icy Spire"
    ],
    keywords: {
      list: [
        "Frozen Ascension",
        "Snowbound Crest",
        "Chill Dominion",
        "Icy Perdition",
        "Frosted Exaltation",
        "Glacial Omen",
        "Winter's Bane",
        "Snowclad Requiem",
        "Frozen Eruption",
        "Icy Veil",
        "Frostbound Shroud",
        "Glacial Lament",
        "Winter's Curse",
        "Snowbound Dirge",
        "Frozen Twilight",
        "Icy Shiver",
        "Frosted Echo",
        "Glacial Sigh",
        "Winter's Grasp",
        "Snowclad Veil",
        "Frozen Crest",
        "Icy Manifest",
        "Frostbound Dominion",
        "Glacial Requiem",
        "Winter's Solace",
        "Snowbound Ascension",
        "Frozen Aegis",
        "Icy Shroud",
        "Frosted Mourning",
        "Glacial Howl",
        "Winter's Ire",
        "Snowclad Summit",
        "Frozen Dusk",
        "Icy Exile",
        "Frostbound Lament",
        "Glacial Whisper",
        "Winter's Sorrow",
        "Snowbound Mourn",
        "Frozen Austerity",
        "Icy Elegy",
        "Frosted Lull",
        "Glacial Eulogy",
        "Winter's Dirge",
        "Snowclad Ascension",
        "Frozen Veil",
        "Icy Requiem",
        "Frostbound Echo",
        "Glacial Aegis",
        "Winter's Veil",
        "Snowbound Shiver",
        "Frozen Dominion",
        "Icy Lament"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  dune: {
    chance: 15,
    color: "#f7e8d0",
    size: 50,
    names: [
      "Scorched Expanse",
      "Desert of Desolation",
      "Burnt Mirage",
      "Ashen Sands",
      "Sunstroke Barrens",
      "Dusk Dunes",
      "Bleak Sands",
      "Crimson Expanse",
      "Scalded Wastes",
      "Flaming Mirage",
      "Cinder Dunes",
      "Sunbaked Barrens",
      "Searing Sands",
      "Dustbound Expanse",
      "Infernal Dunes",
      "Charred Mirage",
      "Blazing Sands",
      "Ashen Wastes",
      "Sunstroke Expanse",
      "Dusk Sands",
      "Bleak Dunes",
      "Crimson Wastes",
      "Scalded Expanse",
      "Flaming Dunes",
      "Cinder Sands",
      "Sunbaked Dunes",
      "Searing Expanse",
      "Dustbound Sands",
      "Infernal Expanse",
      "Charred Dunes",
      "Blazing Expanse",
      "Ashen Mirage",
      "Sunstroke Sands",
      "Dusk Expanse",
      "Bleak Mirage",
      "Crimson Dunes",
      "Scalded Sands",
      "Flaming Expanse",
      "Cinder Dunes",
      "Sunbaked Mirage",
      "Searing Sands",
      "Dustbound Dunes",
      "Infernal Sands",
      "Charred Expanse",
      "Blazing Dunes",
      "Ashen Expanse",
      "Sunstroke Dunes",
      "Dusk Mirage",
      "Bleak Expanse",
      "Crimson Sands",
      "Scalded Dunes"
    ],
    keywords: {
      list: [
        "Arid Torment",
        "Scorched Void",
        "Searing Mirage",
        "Sunburnt Expanse",
        "Dust of Desolation",
        "Barren Solace",
        "Parched Fate",
        "Infernal Heat",
        "Cinder Blaze",
        "Flaming Drought",
        "Burning Wastes",
        "Ashen Grit",
        "Scalded Ember",
        "Duststorm",
        "Sunscorched",
        "Arid Dusk",
        "Searing Heat",
        "Sunburnt Mirage",
        "Dust of Ruin",
        "Barren Ember",
        "Parched Void",
        "Infernal Sear",
        "Cinder Storm",
        "Flaming Dusk",
        "Burning Mirage",
        "Ashen Scorch",
        "Scalded Dunes",
        "Dustveil",
        "Sunscorched Grit",
        "Arid Blaze",
        "Searing Dusk",
        "Sunburnt Solace",
        "Dust of Fate",
        "Barren Scorch",
        "Parched Ember",
        "Infernal Mirage",
        "Cinder Dusk",
        "Flaming Solace",
        "Burning Dunes",
        "Ashen Expanse",
        "Scalded Mirage",
        "Duststorm Sear",
        "Sunscorched Void",
        "Arid Ember",
        "Searing Storm",
        "Sunburnt Dunes",
        "Dustveil Mirage",
        "Barren Heat",
        "Parched Scorch",
        "Infernal Dune"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  hills: {
    chance: 15,
    color: "#d0f7d0",
    size: 50,
    names: [
      "Rolling Shadows",
      "Mournful Rise",
      "Gloom Knolls",
      "Verdant Abyss",
      "Twilight Mounds",
      "Somber Hills",
      "Faded Ridges",
      "Forsaken Knolls",
      "Dusky Mounds",
      "Grim Elevation",
      "Shadowed Bluff",
      "Ebon Hills",
      "Dusked Rise",
      "Bleak Knolls",
      "Waning Mounds",
      "Gloaming Hills",
      "Misty Rise",
      "Sable Knolls",
      "Forsworn Mounds",
      "Twilight Ridge",
      "Somber Bluff",
      "Rolling Dusk",
      "Mournful Knolls",
      "Gloomy Mounds",
      "Verdant Dusk",
      "Twilight Elevation",
      "Sombre Hills",
      "Faded Bluff",
      "Forsaken Rise",
      "Dusky Knolls",
      "Grim Mounds",
      "Shadowed Ridges",
      "Ebon Rise",
      "Dusked Knolls",
      "Bleak Mounds",
      "Waning Ridges",
      "Gloaming Bluff",
      "Misty Knolls",
      "Sable Mounds",
      "Forsworn Rise",
      "Twilight Bluff",
      "Somber Knolls",
      "Rolling Dusklands",
      "Mournful Elevation",
      "Gloom Hillock",
      "Verdant Mound",
      "Twilight Knoll",
      "Sombre Mounds",
      "Faded Elevation",
      "Forsaken Bluff",
      "Dusky Rise",
      "Grim Knoll"
    ],
    keywords: {
      list: [
        "Gentle Sorrow",
        "Shade's Climb",
        "Moss of Mourning",
        "Fertile Gloom",
        "Green Dusk",
        "Rolling Lament",
        "Mournful Ascent",
        "Dusky Rise",
        "Forsworn Slope",
        "Shadowed Knoll",
        "Ebon Climb",
        "Dusked Ascent",
        "Bleak Rise",
        "Waning Slope",
        "Gloaming Mound",
        "Misty Ascension",
        "Sable Slope",
        "Forsworn Knoll",
        "Twilight Climb",
        "Somber Ascent",
        "Rolling Knoll",
        "Mournful Slope",
        "Gloomy Rise",
        "Verdant Lament",
        "Twilight Ascent",
        "Sombre Knoll",
        "Faded Climb",
        "Forsaken Rise",
        "Dusky Slope",
        "Grim Ascension",
        "Shadowed Mound",
        "Ebon Knoll",
        "Dusked Slope",
        "Bleak Ascension",
        "Waning Climb",
        "Gloaming Rise",
        "Misty Knoll",
        "Sable Ascension",
        "Forsworn Slope",
        "Twilight Mound",
        "Somber Climb",
        "Rolling Ascent",
        "Mournful Mound",
        "Gloomy Knoll",
        "Verdant Climb",
        "Twilight Slope",
        "Sombre Ascension",
        "Faded Mound",
        "Forsaken Slope",
        "Dusky Ascension",
        "Grim Climb"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  snowhills: {
    chance: 15,
    color: "#d0f7fa",
    size: 50,
    names: [
      "Icy Knolls",
      "Frosted Mounds",
      "Snowy Rise",
      "Chill Hills",
      "Glacial Undulation",
      "Wintry Knolls",
      "Icy Mounds",
      "Frosted Rise",
      "Snowbound Hills",
      "Chill Knolls",
      "Glacial Mounds",
      "Wintry Rise",
      "Icy Bluff",
      "Frosted Knolls",
      "Snowy Mounds",
      "Chill Rise",
      "Glacial Knolls",
      "Wintry Mounds",
      "Icy Elevation",
      "Frosted Slope",
      "Snowbound Knolls",
      "Chill Mounds",
      "Glacial Rise",
      "Wintry Bluff",
      "Icy Ridge",
      "Frosted Undulation",
      "Snowy Knolls",
      "Chill Elevation",
      "Glacial Slope",
      "Wintry Undulation",
      "Icy Crest",
      "Frosted Crest",
      "Snowbound Rise",
      "Chill Crest",
      "Glacial Mound",
      "Wintry Knoll",
      "Icy Undulation",
      "Frosted Bluff",
      "Snowy Ridge",
      "Chill Knoll",
      "Glacial Elevation",
      "Wintry Slope",
      "Icy Mound",
      "Frosted Undulation",
      "Snowbound Knolls",
      "Chill Ridge",
      "Glacial Crest",
      "Wintry Mound",
      "Icy Slope",
      "Frosted Rise",
      "Snowy Crest",
      "Chill Undulation",
      "Glacial Knoll",
      "Wintry Rise"
    ],
    keywords: {
      list: [
        "Icy Wane",
        "Frosted Slope",
        "Chilled Ascent",
        "Snow Veil",
        "Wintry Crest",
        "Icy Drift",
        "Frosted Climb",
        "Chill Undulation",
        "Snowbound Ascent",
        "Wintry Drift",
        "Icy Descent",
        "Frosted Mourn",
        "Chill Crest",
        "Snow Veil",
        "Wintry Ascent",
        "Icy Lull",
        "Frosted Drift",
        "Chill Shiver",
        "Snowbound Crest",
        "Wintry Hush",
        "Icy Ascent",
        "Frosted Whisper",
        "Chill Descent",
        "Snowbound Lull",
        "Wintry Sigh",
        "Icy Whisper",
        "Frosted Shiver",
        "Chill Hush",
        "Snowbound Descent",
        "Wintry Mourn",
        "Icy Shiver",
        "Frosted Echo",
        "Chill Whisper",
        "Snowbound Ascent",
        "Wintry Drift",
        "Icy Descent",
        "Frosted Mourn",
        "Chill Crest",
        "Snowbound Lull",
        "Wintry Whisper",
        "Icy Ascent",
        "Frosted Drift",
        "Chill Shiver",
        "Snowbound Crest",
        "Wintry Hush",
        "Icy Whisper",
        "Frosted Echo",
        "Chill Hush",
        "Snowbound Descent",
        "Wintry Mourn",
        "Icy Shiver",
        "Frosted Whisper"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  volcano: {
    chance: 10,
    color: "#fef2e8",
    size: 50,
    names: [
      "Infernal Crater",
      "Blazing Maelstrom",
      "Scorching Caldera",
      "Fiery Abyss",
      "Molten Vent",
      "Burning Core",
      "Flaming Summit",
      "Cinder Cone",
      "Ashen Volcano",
      "Lava Spire",
      "Inferno Peak",
      "Ember Crater",
      "Seething Vent",
      "Scalding Maelstrom",
      "Blistering Caldera",
      "Flaming Abyss",
      "Molten Rift",
      "Burning Summit",
      "Fiery Crater",
      "Cinder Maelstrom",
      "Ashen Peak",
      "Lava Cone",
      "Infernal Spire",
      "Ember Volcano",
      "Seething Core",
      "Scorching Rift",
      "Blazing Vent",
      "Molten Caldera",
      "Burning Abyss",
      "Fiery Summit",
      "Cinder Crater",
      "Ashen Maelstrom",
      "Lava Peak",
      "Inferno Cone",
      "Ember Spire",
      "Seething Volcano",
      "Scalding Core",
      "Blistering Rift",
      "Flaming Vent",
      "Molten Abyss",
      "Burning Cone",
      "Fiery Maelstrom",
      "Cinder Summit",
      "Ashen Rift",
      "Lava Vent",
      "Infernal Caldera",
      "Ember Abyss",
      "Seething Summit",
      "Scorching Cone",
      "Blazing Rift",
      "Molten Vent",
      "Burning Volcano"
    ],
    keywords: {
      list: [
        "Eruptive Fury",
        "Fiery Cataclysm",
        "Lava Burst",
        "Blazing Tempest",
        "Molten Rage",
        "Infernal Roar",
        "Flame Surge",
        "Cinder Storm",
        "Ashen Outburst",
        "Scorching Eruption",
        "Burning Fury",
        "Fiery Outburst",
        "Lava Surge",
        "Blazing Roar",
        "Molten Tempest",
        "Infernal Burst",
        "Flame Eruption",
        "Cinder Roar",
        "Ashen Fury",
        "Scorching Storm",
        "Burning Tempest",
        "Fiery Burst",
        "Lava Roar",
        "Blazing Surge",
        "Molten Outburst",
        "Infernal Storm",
        "Flame Burst",
        "Cinder Eruption",
        "Ashen Tempest",
        "Scorching Fury",
        "Burning Outburst",
        "Fiery Surge",
        "Lava Burst",
        "Blazing Tempest",
        "Molten Roar",
        "Infernal Eruption",
        "Flame Storm",
        "Cinder Burst",
        "Ashen Surge",
        "Scorching Roar",
        "Burning Storm",
        "Fiery Tempest",
        "Lava Outburst",
        "Blazing Burst",
        "Molten Surge",
        "Infernal Roar",
        "Flame Eruption",
        "Cinder Storm",
        "Ashen Tempest",
        "Scorching Burst",
        "Burning Surge",
        "Fiery Roar"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  badvolcano: {
    chance: 10,
    color: "#fef2e8",
    size: 50,
    names: [
      "Corrupted Inferno",
      "Cursed Pyre",
      "Defiled Volcano",
      "Malevolent Eruption",
      "Blighted Crater",
      "Demon's Maw",
      "Accursed Vent",
      "Vile Caldera",
      "Venomous Maelstrom",
      "Dreadful Blaze",
      "Corrupted Caldera",
      "Cursed Abyss",
      "Defiled Summit",
      "Malevolent Crater",
      "Blighted Vent",
      "Demon's Inferno",
      "Accursed Maelstrom",
      "Vile Rift",
      "Venomous Blaze",
      "Dreadful Pyre",
      "Corrupted Vent",
      "Cursed Summit",
      "Defiled Crater",
      "Malevolent Abyss",
      "Blighted Maelstrom",
      "Demon's Vent",
      "Accursed Rift",
      "Vile Inferno",
      "Venomous Caldera",
      "Dreadful Maelstrom",
      "Corrupted Pyre",
      "Cursed Vent",
      "Defiled Summit",
      "Malevolent Crater",
      "Blighted Abyss",
      "Demon's Maelstrom",
      "Accursed Vent",
      "Vile Rift",
      "Venomous Inferno",
      "Dreadful Caldera",
      "Corrupted Maelstrom",
      "Cursed Abyss",
      "Defiled Vent",
      "Malevolent Summit",
      "Blighted Crater",
      "Demon's Abyss",
      "Accursed Maelstrom",
      "Vile Vent",
      "Venomous Rift",
      "Dreadful Inferno",
      "Corrupted Summit",
      "Cursed Maelstrom",
      "Defiled Abyss"
    ],
    keywords: {
      list: [
        "Venomous Blaze",
        "Malevolent Eruption",
        "Corrupted Fury",
        "Accursed Roar",
        "Defiled Burst",
        "Demon's Outburst",
        "Vile Surge",
        "Cursed Tempest",
        "Blighted Rage",
        "Dreadful Eruption",
        "Venomous Roar",
        "Malevolent Burst",
        "Corrupted Surge",
        "Accursed Storm",
        "Defiled Fury",
        "Demon's Surge",
        "Vile Outburst",
        "Cursed Roar",
        "Blighted Tempest",
        "Dreadful Burst",
        "Venomous Storm",
        "Malevolent Surge",
        "Corrupted Outburst",
        "Accursed Fury",
        "Defiled Roar",
        "Demon's Tempest",
        "Vile Burst",
        "Cursed Surge",
        "Blighted Storm",
        "Dreadful Fury",
        "Venomous Outburst",
        "Malevolent Roar",
        "Corrupted Tempest",
        "Accursed Burst",
        "Defiled Surge",
        "Demon's Fury",
        "Vile Roar",
        "Cursed Tempest",
        "Blighted Outburst",
        "Dreadful Surge",
        "Venomous Fury",
        "Malevolent Tempest",
        "Corrupted Burst",
        "Accursed Surge",
        "Defiled Storm",
        "Demon's Outburst",
        "Vile Fury",
        "Cursed Roar",
        "Blighted Tempest",
        "Dreadful Burst",
        "Venomous Surge",
        "Malevolent Outburst"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  snowvolcano: {
    chance: 10,
    color: "#e0f7fa",
    size: 50,
    names: [
      "Frozen Pyre",
      "Icy Caldera",
      "Glacial Eruption",
      "Frostbound Volcano",
      "Snowbound Crater",
      "Chill Inferno",
      "Icy Maw",
      "Frosted Vent",
      "Glacial Abyss",
      "Winter's Pyre",
      "Frozen Caldera",
      "Icy Eruption",
      "Frostbound Crater",
      "Snowbound Vent",
      "Chill Caldera",
      "Icy Abyss",
      "Frosted Pyre",
      "Glacial Vent",
      "Winter's Caldera",
      "Frozen Eruption",
      "Icy Crater",
      "Frostbound Vent",
      "Snowbound Abyss",
      "Chill Pyre",
      "Icy Caldera",
      "Frosted Eruption",
      "Glacial Crater",
      "Winter's Vent",
      "Frozen Abyss",
      "Icy Pyre",
      "Frostbound Caldera",
      "Snowbound Eruption",
      "Chill Crater",
      "Icy Vent",
      "Frosted Abyss",
      "Glacial Pyre",
      "Winter's Eruption",
      "Frozen Vent",
      "Icy Abyss",
      "Frostbound Pyre",
      "Snowbound Caldera",
      "Chill Eruption",
      "Icy Crater",
      "Frosted Vent",
      "Glacial Abyss",
      "Winter's Pyre",
      "Frozen Caldera",
      "Icy Eruption",
      "Frostbound Crater",
      "Snowbound Vent",
      "Chill Abyss",
      "Icy Pyre"
    ],
    keywords: {
      list: [
        "Chilled Eruption",
        "Frostfire",
        "Icy Burst",
        "Glacial Surge",
        "Snowbound Roar",
        "Winter's Blast",
        "Frozen Outburst",
        "Chill Inferno",
        "Frosted Fury",
        "Icy Tempest",
        "Glacial Burst",
        "Snowbound Surge",
        "Winter's Eruption",
        "Frozen Roar",
        "Chill Burst",
        "Frostfire Surge",
        "Icy Outburst",
        "Glacial Tempest",
        "Snowbound Blast",
        "Winter's Fury",
        "Frozen Burst",
        "Chill Surge",
        "Frostfire Roar",
        "Icy Blast",
        "Glacial Outburst",
        "Snowbound Tempest",
        "Winter's Burst",
        "Frozen Surge",
        "Chill Roar",
        "Frostfire Outburst",
        "Icy Tempest",
        "Glacial Roar",
        "Snowbound Burst",
        "Winter's Surge",
        "Frozen Blast",
        "Chill Outburst",
        "Frostfire Tempest",
        "Icy Roar",
        "Glacial Burst",
        "Snowbound Surge",
        "Winter's Outburst",
        "Frozen Tempest",
        "Chill Blast",
        "Frostfire Roar",
        "Icy Outburst",
        "Glacial Surge",
        "Snowbound Tempest",
        "Winter's Burst",
        "Frozen Roar",
        "Chill Surge",
        "Frostfire Outburst",
        "Icy Tempest"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  },

  badmountain: {
    chance: 10,
    color: "#d0d0d0",
    size: 70,
    names: [
      "Wretched Obsidian",
      "Blighted Monolith",
      "Cursed Peak",
      "Defiled Summit",
      "Doomed Mountain",
      "Forsaken Crag",
      "Grievous Pinnacle",
      "Dismal Mount",
      "Accursed Rock",
      "Mournful Height",
      "Wretched Apex",
      "Blighted Spire",
      "Cursed Colossus",
      "Defiled Ridge",
      "Doomed Summit",
      "Forsaken Peak",
      "Grievous Monolith",
      "Dismal Crag",
      "Accursed Pinnacle",
      "Mournful Obelisk",
      "Wretched Height",
      "Blighted Rock",
      "Cursed Eminence",
      "Defiled Monolith",
      "Doomed Pinnacle",
      "Forsaken Summit",
      "Grievous Crag",
      "Dismal Peak",
      "Accursed Ridge",
      "Mournful Mount",
      "Wretched Monolith",
      "Blighted Apex",
      "Cursed Crag",
      "Defiled Summit",
      "Doomed Colossus",
      "Forsaken Rock",
      "Grievous Pinnacle",
      "Dismal Obelisk",
      "Accursed Mount",
      "Mournful Rock",
      "Wretched Ridge",
      "Blighted Eminence",
      "Cursed Mount",
      "Defiled Apex",
      "Doomed Monolith",
      "Forsaken Crag",
      "Grievous Summit",
      "Dismal Rock",
      "Accursed Colossus",
      "Mournful Pinnacle",
      "Wretched Summit",
      "Blighted Ridge",
      "Cursed Obelisk",
      "Defiled Peak"
    ],
    keywords: {
      list: [
        "Defiled Ascent",
        "Damned Crest",
        "Accursed Summit",
        "Forsworn Elevation",
        "Doomed Climb",
        "Wretched Rise",
        "Blighted Pinnacle",
        "Cursed Apex",
        "Defiled Peak",
        "Damned Ridge",
        "Accursed Elevation",
        "Forsworn Summit",
        "Doomed Obelisk",
        "Wretched Crag",
        "Blighted Height",
        "Cursed Monolith",
        "Defiled Ridge",
        "Damned Summit",
        "Accursed Mount",
        "Forsworn Pinnacle",
        "Doomed Crest",
        "Wretched Obelisk",
        "Blighted Climb",
        "Cursed Summit",
        "Defiled Elevation",
        "Damned Apex",
        "Accursed Crag",
        "Forsworn Rise",
        "Doomed Pinnacle",
        "Wretched Mount",
        "Blighted Ridge",
        "Cursed Elevation",
        "Defiled Ascent",
        "Damned Crest",
        "Accursed Summit",
        "Forsworn Elevation",
        "Doomed Climb",
        "Wretched Rise",
        "Blighted Pinnacle",
        "Cursed Apex",
        "Defiled Peak",
        "Damned Ridge",
        "Accursed Elevation",
        "Forsworn Summit",
        "Doomed Obelisk",
        "Wretched Crag",
        "Blighted Height",
        "Cursed Monolith",
        "Defiled Ridge",
        "Damned Summit",
        "Accursed Mount",
        "Forsworn Pinnacle"
      ],
      weights: [
        25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
        15, 14, 13, 12, 11, 10, 9, 8, 7, 6,
        5, 5, 5, 5,
        4, 4, 4, 4,
        3, 3, 3, 3,
        2, 2, 2, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
    }
  }
};

export const presets = {
    balanced: {
      water: 9,
      wetland: 8,
      plains: 17,
      forest: 12,
      mountain: 7,
      urban: 4,
      ruins: 3,
      snow: 6,
      snowmountain: 5,
      dune: 6,
      hills: 5,
      snowhills: 5,
      volcano: 4,
      badvolcano: 3,
      snowvolcano: 3,
      badmountain: 3
    },
    waterHeavy: {
      water: 22,
      wetland: 8,
      plains: 12,
      forest: 10,
      mountain: 9,
      urban: 4,
      ruins: 3,
      snow: 5,
      snowmountain: 5,
      dune: 5,
      hills: 5,
      snowhills: 4,
      volcano: 3,
      badvolcano: 2,
      snowvolcano: 2,
      badmountain: 1
    },
    forestHeavy: {
      water: 9,
      wetland: 6,
      plains: 13,
      forest: 23,
      mountain: 10,
      urban: 4,
      ruins: 3,
      snow: 5,
      snowmountain: 5,
      dune: 5,
      hills: 5,
      snowhills: 4,
      volcano: 3,
      badvolcano: 2,
      snowvolcano: 2,
      badmountain: 1
    },
    normalClustering: {
      water: 1.5,
      wetland: 0.3,
      plains: 0.3,
      forest: 0.3,
      mountain: 1.5,
      urban: 0.1,
      ruins: 0.1,
      snow: 0.3,
      snowmountain: 0.3,
      dune: 0.3,
      hills: 0.3,
      snowhills: 0.3,
      volcano: 0.3,
      badvolcano: 0.3,
      snowvolcano: 0.3,
      badmountain: 0.3
    }
  };
